ProjectManagementSoftware/Models/Project.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using MongoDB.Bson;
using System.ComponentModel.DataAnnotations;
using MongoDB.Bson.Serialization.Attributes;
using System.ComponentModel;

namespace Revoluza.Models
{
    public class Project
    {
        [BsonId]
        public ObjectId ProjectId { get; set; }
        [DisplayName("Name:")]
        public string Name { get; set; }
        [DisplayName("Description:")]
        public string Description { get; set; }
        [DisplayName("Start Date:")]
        public String StartDate { get; set; }
        [DisplayName("End Date:")]
        public String EndDate { get; set; }
        [DisplayName("Url:")]
        public string Url { get; set; }
        [DisplayName("Client:")]
        public string Client { get; set; }
        [DisplayName("Project Manager:")]
        public string Manager { get; set; }
        [DisplayName("Project Manager:")]
        public string ProjectManager { get; set; }
        [DisplayName("Project Completed:")]
        public Boolean IsComplete { get; set; }
        [DisplayName("Is Active:")]
        public Boolean IsActive { get; set; }
        [DisplayName("Total Employees:")]
        public int TotalEmployees { get; set; }
        //public IList<Employee> AssignedTo { get; set; }
    }
}

ProjectManagementSoftware/Controllers/ProjectsController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using MongoDB.Driver;
using MongoDB.Driver.Builders;
using MongoDB.Bson;
using Revoluza.Models;
using System;
using System.Linq;

namespace Revoluza.Controllers
{
    public class ProjectsController : Controller
    {
        private MongoDatabase mongoDatabase;
        public ProjectsController()
        {
            // create connectionstring
            var connect = "mongodb://localhost";
            var Client = new MongoClient(connect);

            // get Reference of server
            var Server = Client.GetServer();

            // get Reference of Database
            mongoDatabase = Server.GetDatabase("School");
        }

        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult GetAll()
        {
            var _project = mongoDatabase.GetCollection<Project>("Project");
            var _employee = mongoDatabase.GetCollection<Employee>("Employee");
            IList<Project> listProject = new List<Project>();
            var getProject = _project.FindAs(typeof(Project), Query.NE("Name", "null"));
            foreach (Project proj in getProject)
            {
                string empId = proj.Manager;
                ObjectId pmId;
                var isValid = ObjectId.TryParse(empId, out pmId);
                if (isValid)
                {
                    var getQuery = Query<Employee>.EQ(e => e.EmpId, pmId);
                    var emp = _employee.FindOne(getQuery);
                    if (emp != null)
                    {
                        proj.ProjectManager = emp.Fullname;
                    }
                }

                listProject.Add(proj);
            }
            return PartialView("GetAll", listProject);
        }

        public PartialViewResult Search(string searchVal)
        {
            var collections = mongoDatabase.GetCollection<Project>("Project");
            IList<Project> listSearchProject = new List<Project>();
            if (searchVal == "")
            {
                var getProject = collections.FindAs(typeof(Project), Query.NE("Name", "null"));
                foreach (Project proj in getProject)
                {
                    listSearchProject.Add(proj);
                }
            }
            else
            {
                var queryProject = Query.Or(
                    Query.Matches("Name", new BsonRegularExpression(searchVal, "i")), 
                    Query.Matches("Description", new BsonRegularExpression(searchVal, "i")),
                    Query.Matches("Url", new BsonRegularExpression(searchVal, "i")), 
                    Query.Matches("Client", new BsonRegularExpression(searchVal, "i")),
                    Query.Matches("StartDate", new BsonRegularExpression(searchVal, "i")),
                    Query.Matches("EndDate", new BsonRegularExpression(searchVal, "i")));
                
                var getProject = collections.Find(queryProject);

                foreach (Project proj in getProject)
                {
                    if (listSearchProject.Contains(proj) == false)
                    {
                        listSearchProject.Add(proj);
                    }
                }
            }
            return PartialView("GetAll", listSearchProject);
        }

        #region create new record
        public PartialViewResult Create()
        {
            IList<Employee> listEmployee = new List<Employee>();
            var _employee = mongoDatabase.GetCollection<Employee>("Employee");
            var getAllEmployees = _employee.FindAs(typeof(Employee), Query.NE("IsActive", false));
            foreach (Employee emp in getAllEmployees)
            {
                listEmployee.Add(emp);
            }
            var selectEmp = new SelectList(listEmployee, "EmpId", "FullName", 1);
            ViewData["Employee"] = selectEmp;

            return PartialView();
        }

        [HttpPost]
        public PartialViewResult Create(Project proj)
        {
            if (ModelState.IsValid)
            {
                var collections = mongoDatabase.GetCollection<Project>("Project");
                collections.Insert(proj);
                var id = proj.ProjectId;
                return GetAll();
            }
            else
            {
                return PartialView(proj);
            }
        }
        #endregion

        #region Edit Record
        public PartialViewResult Edit(string Id)
        {
            var _project = mongoDatabase.GetCollection<Project>("Project");

            ObjectId projectId;
            var isValid = ObjectId.TryParse(Id, out projectId);
            if (isValid)
            {
                var getQuery = Query<Project>.EQ(e => e.ProjectId, projectId);
                var proj = _project.FindOne(getQuery);
                IList<Employee> listEmployee = new List<Employee>();
                var _employee = mongoDatabase.GetCollection<Employee>("Employee");
                var getAllEmployees = _employee.FindAs(typeof(Employee), Query.NE("IsActive", false));
                foreach (Employee emp in getAllEmployees)
                {
                    listEmployee.Add(emp);
                }
                var selectEmp = new SelectList(listEmployee, "EmpId", "FullName", proj.Manager);
                ViewData["Employee"] = selectEmp;

                return PartialView("Edit", proj);
            }
            else
            {
                return PartialView("Edit");
            }
        }

        [HttpPost]
        public PartialViewResult Edit(Project proj, string ProjectId)
        {
            ObjectId projectId;
            var isValid = ObjectId.TryParse(ProjectId, out projectId);
            if (isValid)
            {
                var collections = mongoDatabase.GetCollection<Project>("Project");
                var getQuery = Query<Project>.EQ(e => e.ProjectId, projectId);
                var existingproject = collections.FindOne(getQuery);
                existingproject.Name = proj.Name;
                existingproject.StartDate = proj.StartDate;
                existingproject.EndDate = proj.EndDate;
                existingproject.Manager = proj.Manager;
                existingproject.Description = proj.Description;
                existingproject.Client = proj.Client;
                //existingproject.TotalEmployees = proj.TotalEmployees;
                existingproject.IsComplete = proj.IsComplete;
                existingproject.IsActive = proj.IsActive;
                existingproject.Url = proj.Url;
                // existingproject.AssignedTo = project.AssignedTo;
                collections.Save(existingproject);
                return GetAll();
            }
            else
            {
                return PartialView("Edit");
            }
        }
        #endregion

        #region Get Details By Id
        public PartialViewResult Details(string Id)
        {
            var collections = mongoDatabase.GetCollection<Project>("Project");

            ObjectId projectId;
            var isValid = ObjectId.TryParse(Id, out projectId);
            if (isValid)
            {
                var getQuery = Query<Project>.EQ(e => e.ProjectId, projectId);
                Project proj = collections.FindOne(getQuery);
                var _employee = mongoDatabase.GetCollection<Employee>("Employee");
                string empId = proj.Manager;
                ObjectId pmId;
                isValid = ObjectId.TryParse(empId, out pmId);
                if (isValid)
                {
                    getQuery = Query<Employee>.EQ(e => e.EmpId, pmId);
                    var emp = _employee.FindOne(getQuery);
                    if (emp != null)
                    {
                        proj.ProjectManager = emp.Fullname;
                    }
                }
                return PartialView("Details", proj);
            }
            else
            {
                return PartialView("Error");
            }
        }
        #endregion

        #region Delete Records
        public PartialViewResult Delete(string Id)
        {
            var collections = mongoDatabase.GetCollection<Project>("Project");

            ObjectId projectId;
            var isValid = ObjectId.TryParse(Id, out projectId);
            if (isValid)
            {
                var getQuery = Query<Project>.EQ(e => e.ProjectId, projectId);
                collections.Remove(getQuery);
                return GetAll();
            }
            else
            {
                return PartialView("Error");
            }
        }
        #endregion
    }
}

ProjectManagementSoftware/Views/Projects/Create.cshtml
@model Revoluza.Models.Project

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title">Add New Project</h4>
</div>
<div class="modal-body">
    @using (Ajax.BeginForm("Create", "Projects", new AjaxOptions {
        HttpMethod = "POST",
        UpdateTargetId = "divList", 
        InsertionMode = InsertionMode.Replace, 
        OnSuccess = "closeModal" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "datefield form-control col-md-6", @type="date" } })
                    @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "datefield form-control col-md-6", @type="date" } })
                    @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Client, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Client, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Client, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Manager, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.DropDownList("Manager", (SelectList)ViewData["Employee"],new { @class = "form-control col-md-5" } )
                    @Html.ValidationMessageFor(model => model.Manager, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.IsComplete, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.CheckBox("IsComplete", false, new { @class="form-control", @checked="false" })
                    @Html.ValidationMessageFor(model => model.IsComplete, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.CheckBox("IsActive", true, new { @class="form-control", @checked="true" })
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group modal-footer">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default btn-success" />
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    }
</div>

ProjectManagementSoftware/Views/Projects/Details.cshtml
@model Revoluza.Models.Project 

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title">Details Record</h4>
</div>
<div class="modal-body">
    <div>
        <table class="table table-bordered">
            <tr>
                <td>@Html.DisplayNameFor(model => model.Name)</td>
                <td>@Html.DisplayFor(model => model.Name)</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.Description)</td>
                <td>@Html.DisplayFor(model => model.Description)</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.StartDate)</td>
                <td>@Html.DisplayFor(model => model.StartDate)</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.EndDate)</td>
                <td>@Html.DisplayFor(model => model.EndDate)</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.Url)</td>
                <td>@Html.DisplayFor(model => model.Url)</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.Client)</td>
                <td>@Html.DisplayFor(model => model.Client)</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.ProjectManager)</td>
                <td>@Html.DisplayFor(model => model.ProjectManager)</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.IsComplete)</td>
                <td>@Html.DisplayFor(model => model.IsComplete)</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.IsActive)</td>
                <td>@Html.DisplayFor(model => model.IsActive)</td>
            </tr>
            @*<tr>
                <td>@Html.DisplayNameFor(model => model.TotalEmployees)</td>
                <td>@Html.DisplayFor(model => model.TotalEmployees)</td>
            </tr>*@
        </table>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-info"
            data-dismiss="modal">
        Close
    </button>
</div>

ProjectManagementSoftware/Views/Projects/Edit.cshtml
@model Revoluza.Models.Project

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title">Edit Project</h4>
</div>
<div class="modal-body">

    @using (Ajax.BeginForm("Edit", "Projects", new AjaxOptions
  {
      HttpMethod = "POST",
      UpdateTargetId = "divList",
      InsertionMode = InsertionMode.Replace,
      OnSuccess = "closeModal"
  }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.ProjectId)
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new {  @class = "datefield form-control col-md-6", @type="date"  } })
                    @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new {  @class = "datefield form-control col-md-6", @type="date" } })
                    @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Client, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Client, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Client, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Manager, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.DropDownList("Manager", (SelectList)ViewData["Employee"],new { @class = "form-control col-md-5" } )
                    @Html.ValidationMessageFor(model => model.Manager, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.IsComplete, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.CheckBox("IsComplete", Model.IsComplete, new { @class = "form-control", @checked=Model.IsComplete})
                    @Html.ValidationMessageFor(model => model.IsComplete, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.CheckBox("IsActive", Model.IsActive, new { @class = "form-control", @checked=Model.IsActive})
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group modal-footer">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Update" class="btn btn-default btn-primary" />
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    }
</div>

ProjectManagementSoftware/Views/Projects/GetAll.cshtml
@model IEnumerable<Revoluza.Models.Project>

@{
    var count = 1;
}

<table class="table table-bordered table-striped" style="width: 75%;">
    <thead>
        <tr>
            <th colspan="2" style="text-align: center"><div class="input-group"><input type="text" id="filterValue" class="form-control" style="width:125px;" placeholder="Search for..."><span class="input-group-btn"><button class="btn btn-default btnSearchProj" id="btnSearchProj" type="button">Go!</button></div></th>
            <th colspan="5" style="text-align: center;">Project List<span class="btn btn-xs btn-success btnCreate" id="btnCreate" style="float:right;">Create New</span></th>
        </tr>
        <tr class="success">
            <th>SNo.</th>
            <th>Name</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Project Manager</th>
            <th>Client</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var proj in Model)
        {
            <tr>
                <td>@(count++)</td>
                <td>@proj.Name</td>
                <td>@proj.StartDate</td>
                <td>@proj.EndDate</td>
                <td>@proj.ProjectManager</td>
                <td>@proj.Client</td>
                <td>
                    <span class="btn btn-xs btn-primary btnEdit" id="edit_@proj.ProjectId">Edit</span>
                    <span class="btn btn-xs btn-info btnDetails" id="delails_@proj.ProjectId">Details</span>
                    <span class="btn btn-xs btn-danger btnDelete" id="delete_@proj.ProjectId">Delete</span>
                    <span class="btn btn-xs btn-success btnaddTask" id="addTask_@proj.ProjectId">Add Task</span>
                </td>
            </tr>
        }
    </tbody>
</table>

ProjectManagementSoftware/Views/Projects/Index.cshtml
@{
    ViewData["Title"] = "Projects Page";
}
<script src="~/Scripts/bootbox.min.js"></script>
<script src="~/js/Project.js"></script>

<div class="clearfix"><img src="~/Content/images/Ameba.jpg" width="500" height="66" style="float:left" /></div>
<br />
<br />
<br />
<div class="row" id="divList">

</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" id="modelContent">

        </div>
    </div>
</div>