ProjectManagementSoftware/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using MongoDB.Bson;
using System.ComponentModel.DataAnnotations;
using MongoDB.Bson.Serialization.Attributes;
using System.ComponentModel;

namespace Revoluza.Models
{
    public class Employee
    {
        [BsonId]
        public ObjectId EmpId { get; set; }
        [DisplayName("Join Date:")]
        public String JoinDate { get; set; }
        [DisplayName("Date Of Birth:")]
        public String DateOfBirth { get; set; }
        [DisplayName("First Name:")]
        public string FirstName { get; set; }
        [DisplayName("Last Name:")]
        public string LastName { get; set; }
        [DisplayName("Designation:")]
        public string Designation { get; set; }
        [DisplayName("Department:")]
        public string Department { get; set; }
        [DisplayName("EMail:")]
        public string Email { get; set; }
        [DisplayName("Gender:")]
        public string Gender { get; set; }
        [DisplayName("Salary:")]
        public string Salary { get; set; }
        public string ReportingTo { get; set; }
        [DisplayName("Reporting To:")]
        public string ReportingHead { get; set; }
        [DisplayName("Is Reporting Head:")]
        public Boolean IsReportingHead { get; set; }
        [DisplayName("Is Active:")]
        public Boolean IsActive { get; set; }
        [DisplayName("Employee Name:")]
        public string Fullname
        {
            get
            {
                return string.Format("{0} {1}", FirstName, LastName);
            }
        }

        //[ScaffoldColumn(false)]
        //public IList<Comment> Comments { get; set; }
    }
}

ProjectManagementSoftware/Controllers/EmployeesController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using MongoDB.Driver;
using MongoDB.Driver.Builders;
using MongoDB.Bson;
using Revoluza.Models;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Revoluza.Controllers
{
    public class EmployeesController : Controller
    {
        private MongoDatabase mongoDatabase;
        public EmployeesController()
        {
            // create connectionstring
            var connect = "mongodb://localhost";
            var Client = new MongoClient(connect);

            // get Reference of server
            var Server = Client.GetServer();

            // get Reference of Database
            mongoDatabase = Server.GetDatabase("School");
        }

        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult GetAll()
        {
            var _employee = mongoDatabase.GetCollection<Employee>("Employee");
            IList<Employee> listEmployee = new List<Employee>();
            var getEmployee = _employee.FindAs(typeof(Employee), Query.NE("IsActive", false));
            foreach (Employee emp in getEmployee)
            {
                string empId = emp.ReportingTo;
                ObjectId pmId;
                var isValid = ObjectId.TryParse(empId, out pmId);
                if (isValid)
                {
                    var getQuery = Query<Employee>.EQ(e => e.EmpId, pmId);
                    var rtemp = _employee.FindOne(getQuery);
                    if (rtemp != null)
                    {
                        emp.ReportingHead = rtemp.Fullname;
                    }
                }
                listEmployee.Add(emp);
            }
            return PartialView("GetAll", listEmployee);
        }

        public PartialViewResult Search(string searchVal)
        {
            var collections = mongoDatabase.GetCollection<Employee>("Employee");
            IList<Employee> listEmployee = new List<Employee>();

            if (searchVal == "")
            {
                var getEmployee = collections.FindAs(typeof(Employee), Query.NE("IsActive", false));
                foreach (Employee emp in getEmployee)
                {
                    listEmployee.Add(emp);
                }
            }
            else
            {
                var queryEmployee = Query.Or(
                    Query.Matches("FirstName", new BsonRegularExpression(searchVal, "i")),
                    Query.Matches("LastName", new BsonRegularExpression(searchVal, "i")),
                    Query.Matches("Department", new BsonRegularExpression(searchVal, "i")),
                    Query.Matches("Designation", new BsonRegularExpression(searchVal, "i")),
                    Query.Matches("DateOfBirth", new BsonRegularExpression(searchVal, "i")),
                    Query.Matches("Email", new BsonRegularExpression(searchVal, "i")));

                var getEmployee = collections.Find(queryEmployee);

                foreach (Employee emp in getEmployee)
                {
                    if (!listEmployee.Contains(emp))
                    {
                        listEmployee.Add(emp);
                    }
                }
            }
            return PartialView("GetAll", listEmployee);
        }

        #region create new record
        public PartialViewResult Create()
        {
            IList<Employee> listEmployee = new List<Employee>();
            var _employee = mongoDatabase.GetCollection<Employee>("Employee");
            var getReportHead = _employee.FindAs(typeof(Employee), Query.EQ("IsReportingHead", true));
            foreach (Employee emp in getReportHead)
            {
                listEmployee.Add(emp);
            }
            if (listEmployee.Count > 0)
            {
                var selectEmp = new SelectList(listEmployee, "EmpId", "FullName", 0);
                ViewData["Employee"] = selectEmp;
            }

            return PartialView();
        }

        [HttpPost]
        public PartialViewResult Create(Employee emp)
        {
            if (ModelState.IsValid)
            {
                var _employee = mongoDatabase.GetCollection<Employee>("Employee");
                string empId = emp.ReportingTo;
                ObjectId pmId;
                var isValid = ObjectId.TryParse(empId, out pmId);
                if (isValid)
                {
                    var getQuery = Query<Employee>.EQ(e => e.EmpId, pmId);
                    var rtemp = _employee.FindOne(getQuery);
                    if (rtemp != null)
                    {
                        emp.ReportingHead = rtemp.Fullname;
                    }
                }
                _employee.Insert(emp);
                var id = emp.EmpId;
                return GetAll();
            }
            else
            {
                return PartialView(emp);
            }
        }
        #endregion

        #region Edit Record
        public PartialViewResult Edit(string Id)
        {
            var collections = mongoDatabase.GetCollection<Employee>("Employee");

            ObjectId empId;
            var isValid = ObjectId.TryParse(Id, out empId);
            if (isValid)
            {
                var getQuery = Query<Employee>.EQ(e => e.EmpId, empId);
                var emp = collections.FindOne(getQuery);
                var _employee = mongoDatabase.GetCollection<Employee>("Employee");
                IList<Employee> listEmployee = new List<Employee>();
                var getReportingHead = _employee.FindAs(typeof(Employee), Query.EQ("IsReportingHead", true));
                foreach (Employee rthead in getReportingHead)
                {
                    listEmployee.Add(rthead);
                }
                if (listEmployee.Count > 0)
                {
                    var selectEmp = new SelectList(listEmployee, "EmpId", "FullName", emp.ReportingTo);
                    ViewData["Employee"] = selectEmp;
                }
                return PartialView("Edit", emp);
            }
            else
            {
                return PartialView("Edit");
            }

        }

        [HttpPost]
        public PartialViewResult Edit(Employee emp, string EmpId)
        {
            ObjectId empId;
            var isValid = ObjectId.TryParse(EmpId, out empId);
            if (isValid)
            {
                var collections = mongoDatabase.GetCollection<Employee>("Employee");
                var getQuery = Query<Employee>.EQ(e => e.EmpId, empId);
                var existingemp = collections.FindOne(getQuery);
                existingemp.LastName = emp.LastName;
                existingemp.FirstName = emp.FirstName;
                existingemp.Email = emp.Email;
                existingemp.Designation = emp.Designation;
                existingemp.ReportingTo = emp.ReportingTo;
                existingemp.Department = emp.Department;
                existingemp.DateOfBirth = emp.DateOfBirth;
                existingemp.Gender = emp.Gender;
                existingemp.Salary = emp.Salary;
                existingemp.IsReportingHead = emp.IsReportingHead;
                existingemp.IsActive = emp.IsActive;
                collections.Save(existingemp);
                return GetAll();
            }
            else
            {
                return PartialView("Edit");
            }
        }
        #endregion

        #region Get Details By Id
        public PartialViewResult Details(string Id)
        {
            var _employee = mongoDatabase.GetCollection<Employee>("Employee");

            ObjectId empId;
            var isValid = ObjectId.TryParse(Id, out empId);
            if (isValid)
            {
                var getQuery = Query<Employee>.EQ(e => e.EmpId, empId);
                Employee emp = _employee.FindOne(getQuery);
                if (emp.ReportingTo != null && emp.ReportingHead == null)
                {
                    string revoluzaId = emp.ReportingTo;
                    ObjectId pleasurebuilderId;
                    isValid = ObjectId.TryParse(revoluzaId, out pleasurebuilderId);
                    if (isValid)
                    {
                        getQuery = Query<Employee>.EQ(e => e.EmpId, pleasurebuilderId);
                        var rtemp = _employee.FindOne(getQuery);
                        if (rtemp != null)
                        {
                            emp.ReportingHead = rtemp.Fullname;
                        }
                    }
                }
                return PartialView("Details", emp);
            }
            else
            {

                return PartialView("Error");
            }
        }
        #endregion

        #region Delete Records
        public PartialViewResult Delete(string Id)
        {
            var collections = mongoDatabase.GetCollection<Employee>("Employee");

            ObjectId empId;
            var isValid = ObjectId.TryParse(Id, out empId);
            if (isValid)
            {
                var getQuery = Query<Employee>.EQ(e => e.EmpId, empId);
                collections.Remove(getQuery);
                return GetAll();
            }
            else
            {
                return PartialView("Error");
            }
        }
        #endregion
        
    }
}

ProjectManagementSoftware/Views/Employees/Create.cshtml
@model Revoluza.Models.Employee

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title">Add New Employee</h4>
</div>
<div class="modal-body">
    @using (Ajax.BeginForm("Create", "Employees", new AjaxOptions {
        HttpMethod = "POST",
        UpdateTargetId = "divList", 
        InsertionMode = InsertionMode.Replace, 
        OnSuccess = "closeModal" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Designation, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Designation, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Designation, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Department, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Department, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.JoinDate, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.JoinDate, new { htmlAttributes = new { @class = "datefield col-md-6 form-control", @type="date" } })
                    @Html.ValidationMessageFor(model => model.JoinDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "datefield col-md-6 form-control", @type="date" } })
                    @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Salary, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ReportingTo, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @*@Html.EditorFor(model => model.ReportingTo, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.DropDownList("ReportingTo", (SelectList)ViewData["Employee"], new { @class = "form-control col-md-5" } )
                    @Html.ValidationMessageFor(model => model.ReportingTo, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.IsReportingHead, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.CheckBox("IsReportingHead", false, new { @class="form-control", @checked="false" })
                    @Html.ValidationMessageFor(model => model.IsReportingHead, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.CheckBox("IsActive", true, new { @class="form-control", @checked="true" })
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group modal-footer">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default btn-success" />
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    }
</div>

ProjectManagementSoftware/Views/Employees/Details.cshtml
@model Revoluza.Models.Employee 

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title">Details Record</h4>
</div>
<div class="modal-body">
    <div>
        <table class="table table-bordered">
            <tr>
                <td>@Html.DisplayNameFor(model => model.FirstName)</td>
                <td>@Html.DisplayFor(model => model.FirstName)</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.LastName)</td>
                <td>@Html.DisplayFor(model => model.LastName)</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.Email)</td>
                <td>@Html.DisplayFor(model => model.Email)</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.Designation)</td>
                <td>@Html.DisplayFor(model => model.Designation)</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.Department)</td>
                <td>@Html.DisplayFor(model => model.Department)</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.Salary)</td>
                <td>@Html.DisplayFor(model => model.Salary)</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.Gender)</td>
                <td>@Html.DisplayFor(model => model.Gender)</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.ReportingHead)</td>
                <td>@Html.DisplayFor(model => model.ReportingHead)</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.IsReportingHead)</td>
                <td>@Html.DisplayFor(model => model.IsReportingHead)</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.IsActive)</td>
                <td>@Html.DisplayFor(model => model.IsActive)</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.DateOfBirth)</td>
                <td>@Html.DisplayFor(model => model.DateOfBirth)</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.JoinDate)</td>
                <td>@Html.DisplayFor(model => model.JoinDate)</td>
            </tr>
        </table>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-info"
            data-dismiss="modal">
        Close
    </button>
</div>

ProjectManagementSoftware/Views/Employees/Edit.cshtml
@model Revoluza.Models.Employee 

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title">Edit Employee</h4>
</div>
<div class="modal-body">

    @using (Ajax.BeginForm("Edit", "Employees", new AjaxOptions
  {
      HttpMethod = "POST",
      UpdateTargetId = "divList",
      InsertionMode = InsertionMode.Replace,
      OnSuccess = "closeModal"
  }))
    {
        @Html.AntiForgeryToken()
         @Html.HiddenFor(model => model.EmpId)
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Designation, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Designation, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Designation, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Department, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Department, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.JoinDate, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.JoinDate, new { htmlAttributes = new { @class = "datefield col-md-6 form-control", @type="date" } })
                    @Html.ValidationMessageFor(model => model.JoinDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "datefield col-md-6 form-control", @type="date" } })
                    @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Salary, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ReportingTo, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.DropDownList("ReportingTo", (SelectList)ViewData["Employee"], new { @class = "form-control col-md-5" } )
                    @Html.ValidationMessageFor(model => model.ReportingTo, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.IsReportingHead, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.CheckBox("IsReportingHead", Model.IsReportingHead, new { @class = "form-control", @checked=Model.IsReportingHead})
                    @Html.ValidationMessageFor(model => model.IsReportingHead, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.CheckBox("IsActive", Model.IsActive, new { @class = "form-control", @checked=Model.IsActive})
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group modal-footer">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Update" class="btn btn-default btn-primary" />
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    }
</div>

ProjectManagementSoftware/Views/Employees/GetAll.cshtml
@model IEnumerable<Revoluza.Models.Employee>
@{
    var count = 1;
}
<table class="table table-bordered table-striped" style="width: 75%;">
    <thead>
        <tr>
            <th colspan="2" style="text-align: center"><div class="input-group"><input type="text" id="filterValue" class="form-control" style="width:125px;" placeholder="Search for..."><span class="input-group-btn"><button class="btn btn-default btnSearch" id="btnSearch" type="button">Go!</button></div></th>
            <th colspan="4" style="text-align: center">Employee List<span class="btn btn-xs btn-success btnCreate" id="btnCreate" style="float:right;">Create New</span></th>
        </tr>
        <tr class="success">
            <th>SNo.</th>
            <th>Employee Name</th>
            <th>Gender</th>
            <th>Department</th>
            <th>Designation</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var emp in Model)
        {
            <tr>
                <td>@(count++)</td>
                <td>@emp.Fullname</td>
                <td>@emp.Gender</td>
                <td>@emp.Department</td>
                <td>@emp.Designation</td>
                <td>
                    <span class="btn btn-xs btn-primary btnEdit" id="edit_@emp.EmpId">Edit</span>
                    <span class="btn btn-xs btn-info btnDetails" id="delails_@emp.EmpId">Details</span>
                    <span class="btn btn-xs btn-danger btnDelete" id="delete_@emp.EmpId">Delete</span>
                </td>
            </tr>
        }
    </tbody>
</table>

ProjectManagementSoftware/Views/Employees/Index.cshtml
@{
    ViewBag.Title = "Employees Page";
}
<script src="~/Scripts/bootbox.min.js"></script>
<script src="~/js/Employee.js"></script>
<div class="clearfix"><img src="~/Content/images/Ameba.jpg" width="500" height="66" style="float:left" /></div>
<br />
<br />
<br />
<div class="row" id="divList">
 
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" id="modelContent">
            
        </div>
    </div>
</div>