ProjectManagementSoftware/Controllers/TicketsController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using MongoDB.Driver;
using MongoDB.Driver.Builders;
using MongoDB.Bson;
using Revoluza.Models;
using System;
using System.Linq;
using System.Configuration;
using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Diagnostics;
using System.Web.Helpers;

namespace Revoluza.Controllers
{
    public class TicketsController : Controller
    {
        private MongoDatabase mongoDatabase;
        public TicketsController()
        {
            // create connectionstring
            var connect = "mongodb://localhost";
            var Client = new MongoClient(connect);

            // get Reference of server
            var Server = Client.GetServer();

            // get Reference of Database
            mongoDatabase = Server.GetDatabase("School");
        }
        //
        // GET: /Tickets/
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult GetAll()
        {
            var _project = mongoDatabase.GetCollection<Project>("Project");
            var _tickets = mongoDatabase.GetCollection<TicketBase>("TicketBase");
            var _employee = mongoDatabase.GetCollection<Employee>("Employee");

            IList<TicketBase> lstTickets = new List<TicketBase>();
            var getTicks = _tickets.FindAs(typeof(TicketBase), Query.NE("Status", "Cancelled"));

            foreach (TicketBase tick in getTicks)
            {
                string empId = tick.AssignedToId;
                ObjectId assId;
                var isValid = ObjectId.TryParse(empId, out assId);
                if (isValid)
                {
                    var getQuery = Query<Employee>.EQ(e => e.EmpId, assId);
                    var rtemp = _employee.FindOne(getQuery);
                    if (rtemp != null)
                    {
                        tick.AssignedTo = rtemp.Fullname;
                    }
                }

                string projId = tick.ProjectId;
                ObjectId projectId;
                isValid = ObjectId.TryParse(projId, out projectId);
                if (isValid)
                {
                    var getQuery = Query<Project>.EQ(e => e.ProjectId, projectId);
                    var proj = _project.FindOne(getQuery);
                    if (proj != null)
                    {
                        tick.ProjectName = proj.Name;
                    }
                }
                lstTickets.Add(tick);
            }
            return PartialView("GetAll", lstTickets);
        }

        #region create new record
        public PartialViewResult Create()
        {
            var _project = mongoDatabase.GetCollection<Project>("Project");
            var _employee = mongoDatabase.GetCollection<Employee>("Employee");

            IList<Project> listProject = new List<Project>();
            var getAllProjects = _project.FindAs(typeof(Project), Query.NE("Name", "null"));
            foreach (Project proj in getAllProjects)
            {
                listProject.Add(proj);
            }
            var selectProj = new SelectList(listProject, "ProjectId", "Name", listProject[0].ProjectId);
            ViewData["Project"] = selectProj;

            IList<Employee> listEmployee = new List<Employee>();
            var getAllEmployees = _employee.FindAs(typeof(Employee), Query.NE("IsActive", false));
            foreach (Employee emp in getAllEmployees)
            {
                listEmployee.Add(emp);
            }
            var selectEmp = new SelectList(listEmployee, "EmpId", "FullName", 1);
            ViewData["Employee"] = selectEmp;

            List<Status> listStatus = new List<Status>();

            Status stT3 = new Status() { Name = "Not Started" };
            listStatus.Add(stT3);
            Status stT1 = new Status() { Name = "In-Process" };
            listStatus.Add(stT1);
            Status stT2 = new Status() { Name = "Complete" };
            listStatus.Add(stT2);
            Status stT5 = new Status() { Name = "Waiting Approval" };
            listStatus.Add(stT5);
            Status stT6 = new Status() { Name = "On Hold" };
            listStatus.Add(stT6);
            Status stT4 = new Status() { Name = "Cancelled" };
            listStatus.Add(stT4);

            var selectSt = new SelectList(listStatus, "Name", "Name", listStatus[0].Name);
            ViewData["Status"] = selectSt;

            List<Status> listPriority = new List<Status>();

            Status stP3 = new Status() { Name = "Very Urgent" };
            listPriority.Add(stP3);
            Status stP1 = new Status() { Name = "Urgent" };
            listPriority.Add(stP1);
            Status stP2 = new Status() { Name = "Normal" };
            listPriority.Add(stP2);

            var selectPriority = new SelectList(listPriority, "Name", "Name", listPriority[0].Name);
            ViewData["Priority"] = selectPriority;

            return PartialView();
        }

        [HttpPost]
        public PartialViewResult SaveTicket(TicketBase tick)
        {
            if (ModelState.IsValid)
            {
                var _tickets = mongoDatabase.GetCollection<TicketBase>("TicketBase");
                _tickets.Insert(tick);
                var id = tick.Id;
                return GetAll();
            }
            else
            {
                return PartialView("Error");
            }
        }

        [HttpPost]
        public PartialViewResult Create(TicketBase tick)
        {
            if (ModelState.IsValid)
            {
                var _tickets = mongoDatabase.GetCollection<TicketBase>("TicketBase");
                _tickets.Insert(tick);
                var id = tick.Id;
                return GetAll();
            }
            else
            {
                return PartialView("Error");
            }
        }
        #endregion

        #region Edit Record
        public PartialViewResult Edit(string Id)
        {
            var _tickets = mongoDatabase.GetCollection<TicketBase>("TicketBase");
            
            ObjectId tickId;
            var isValid = ObjectId.TryParse(Id, out tickId);

            if (isValid)
            {
                var getQuery = Query<TicketBase>.EQ(e => e.Id, tickId);
                var tick = _tickets.FindOne(getQuery);

                var _project = mongoDatabase.GetCollection<Project>("Project");
                var _employee = mongoDatabase.GetCollection<Employee>("Employee");

                ObjectId projId;
                isValid = ObjectId.TryParse(tick.ProjectId, out projId);
                IList<Project> listProject = new List<Project>();
                if (isValid)
                {
                    getQuery = Query<Project>.EQ(e => e.ProjectId, projId);
                    Project proj = _project.FindOne(getQuery);
                    listProject.Add(proj);
                    var selectProj = new SelectList(listProject, "ProjectId", "Name", proj.ProjectId);
                    ViewData["Project"] = selectProj;
                }

                ObjectId empId;
                isValid = ObjectId.TryParse(tick.AssignedToId, out empId);
                IList<Employee> listEmployee = new List<Employee>();
                if (isValid)
                {
                    getQuery = Query<Employee>.EQ(e => e.EmpId, empId);
                    Employee emp = _employee.FindOne(getQuery);
                    listEmployee.Add(emp);
                    var selectEmp = new SelectList(listEmployee, "EmpId", "FullName", tick.AssignedToId);
                    ViewData["Employee"] = selectEmp;
                }

                List<Status> listStatus = new List<Status>();

                Status stT3 = new Status() { Name = "Not Started" };
                listStatus.Add(stT3);
                Status stT1 = new Status() { Name = "In-Process" };
                listStatus.Add(stT1);
                Status stT2 = new Status() { Name = "Complete" };
                listStatus.Add(stT2);
                Status stT5 = new Status() { Name = "Waiting Approval" };
                listStatus.Add(stT5);
                Status stT6 = new Status() { Name = "On Hold" };
                listStatus.Add(stT6);
                Status stT4 = new Status() { Name = "Cancelled" };
                listStatus.Add(stT4);

                var selectSt = new SelectList(listStatus, "Name", "Name", tick.Status);
                ViewData["Status"] = selectSt;

                List<Status> listPriority = new List<Status>();
                Status stP3 = new Status() { Name = "Very Urgent" };
                listPriority.Add(stP3);
                Status stP1 = new Status() { Name = "Urgent" };
                listPriority.Add(stP1);
                Status stP2 = new Status() { Name = "Normal" };
                listPriority.Add(stP2);

                var selectPriority = new SelectList(listPriority, "Name", "Name", tick.Priority);
                ViewData["Priority"] = selectPriority;

                return PartialView("Edit",tick);
            }
            else
            {
                return PartialView("Error");
            }
        }

        [HttpPost]
        public PartialViewResult Edit(TicketBase tick,string Id)
        {
            ObjectId tickId;
            var isValid = ObjectId.TryParse(Id, out tickId);
            if (isValid)
            {
                var _tickets = mongoDatabase.GetCollection<TicketBase>("TicketBase");
                var getQuery = Query<TicketBase>.EQ(e => e.Id, tickId);
                var existingtick = _tickets.FindOne(getQuery);
                existingtick.AssignedToId = tick.AssignedToId;
                existingtick.CloseDate = tick.CloseDate;
                existingtick.CreateDate = tick.CreateDate;
                existingtick.CreatedBy = tick.CreatedBy;

ProjectManagementSoftware/Views/Tickets/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ProjectManagementSoftware/Views/Tickets/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    F-452 3rd Floor<br />
    Phase 8 B Industrial Area<br />
    Mohali, Punjab, India. <br />
    <abbr title="Phone">P:</abbr>
    0172.223.7733
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:info@amebatechnologies.co.in">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:info@amebatechnologies.co.in">Marketing@example.com</a>
</address>

ProjectManagementSoftware/Views/Tickets/Create.cshtml
@model Revoluza.Models.TicketBase 

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title">Add New Ticket</h4>
</div>
<div class="modal-body">
    @using (Ajax.BeginForm("SaveTicket", "Tickets", new AjaxOptions {
        HttpMethod = "POST",
        UpdateTargetId = "divList", 
        InsertionMode = InsertionMode.Replace, 
        OnSuccess = "closeModal" }))
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.ProjectId, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.DropDownList("ProjectId", (SelectList)ViewData["Project"], new { @class = "form-control col-md-5" } ) 
                    @Html.ValidationMessageFor(model => model.ProjectId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.CreateDate, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.CreateDate, new { htmlAttributes = new { @class = "datefield form-control col-md-6", @type="date" } })
                    @Html.ValidationMessageFor(model => model.CreateDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Issue, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.TextAreaFor(model => model.Issue,5,50, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Issue, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Priority, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.DropDownList("Priority", (SelectList)ViewData["Priority"], new { @class = "form-control col-md-5" } ) 
                    @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.AssignedTo, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.DropDownList("AssignedToId", (SelectList)ViewData["Employee"], new { @class = "form-control col-md-5" } ) 
                    @Html.ValidationMessageFor(model => model.AssignedTo, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.DropDownList("Status", (SelectList)ViewData["Status"], new { @class = "form-control col-md-5" } ) 
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.AsOnDate, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.AsOnDate, new { htmlAttributes = new { @class = "datefield form-control col-md-6", @type="date" } })
                    @Html.ValidationMessageFor(model => model.AsOnDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.PercentComplete, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.PercentComplete, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PercentComplete, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.CloseDate, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.CloseDate, new { htmlAttributes = new { @class = "datefield form-control col-md-6", @type="date" } })
                    @Html.ValidationMessageFor(model => model.CloseDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Remarks, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.TextAreaFor(model => model.Remarks,5,50, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group modal-footer">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default btn-success" />
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    }
</div>

ProjectManagementSoftware/Views/Tickets/Details.cshtml
@model Revoluza.Models.TicketBase
 
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title">Ticket Details</h4>
</div>
<div class="modal-body">
    <div>
        <table class="table table-bordered">
            <tr>
                <td>@Html.DisplayNameFor(model => model.ProjectName)</td>
                <td>@Html.DisplayFor(model => model.ProjectName)</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.CreateDate)</td>
                <td>@Html.DisplayFor(model => model.CreateDate)</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.CreatedBy)</td>
                <td>@Html.DisplayFor(model => model.CreatedBy)</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.Issue)</td>
                <td>@Html.DisplayFor(model => model.Issue)</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.Priority)</td>
                <td>@Html.DisplayFor(model => model.Priority)</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.AssignedTo)</td>
                <td>@Html.DisplayFor(model => model.AssignedTo)</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.Status)</td>
                <td>@Html.DisplayFor(model => model.Status)</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.AsOnDate)</td>
                <td>@Html.DisplayFor(model => model.AsOnDate)</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.PercentComplete)</td>
                <td>@Html.DisplayFor(model => model.PercentComplete)</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.CloseDate)</td>
                <td>@Html.DisplayFor(model => model.CloseDate)</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.Remarks)</td>
                <td>@Html.DisplayFor(model => model.Remarks)</td>
            </tr>
        </table>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-info"
            data-dismiss="modal">
        Close
    </button>
</div>

ProjectManagementSoftware/Views/Tickets/Edit.cshtml
@model Revoluza.Models.TicketBase 

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title">Edit Ticket</h4>
</div>
<div class="modal-body">
    @using (Ajax.BeginForm("SaveTicket", "Assigns", new AjaxOptions {
        HttpMethod = "POST",
        UpdateTargetId = "divList", 
        InsertionMode = InsertionMode.Replace, 
        OnSuccess = "closeModal" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.Id)
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.ProjectId, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.DropDownList("ProjectId", (SelectList)ViewData["Project"], new { @class = "form-control col-md-5", @readonly="true" } ) 
                    @Html.ValidationMessageFor(model => model.ProjectId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.CreateDate, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.CreateDate, new { htmlAttributes = new { @class = "datefield form-control col-md-6", @type="date" } })
                    @Html.ValidationMessageFor(model => model.CreateDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Issue, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.TextAreaFor(model => model.Issue,5,50, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Issue, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Priority, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.DropDownList("Priority", (SelectList)ViewData["Priority"], new { @class = "form-control col-md-5" } ) 
                    @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.AssignedTo, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.DropDownList("AssignedTo", (SelectList)ViewData["Employee"], new { @class = "form-control col-md-5" } ) 
                    @Html.ValidationMessageFor(model => model.AssignedTo, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.DropDownList("Status", (SelectList)ViewData["Status"], new { @class = "form-control col-md-5" } ) 
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.AsOnDate, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.AsOnDate, new { htmlAttributes = new { @class = "datefield form-control col-md-6", @type="date" } })
                    @Html.ValidationMessageFor(model => model.AsOnDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.PercentComplete, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.PercentComplete, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PercentComplete, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.CloseDate, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.CloseDate, new { htmlAttributes = new { @class = "datefield form-control col-md-6", @type="date" } })
                    @Html.ValidationMessageFor(model => model.CloseDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Remarks, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.TextAreaFor(model => model.Remarks, 5, 50, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group modal-footer">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Update" class="btn btn-default btn-primary" />
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    }
</div>

ProjectManagementSoftware/Views/Tickets/GetAll.cshtml
@using Revoluza.Models
@model IEnumerable<Revoluza.Models.TicketBase>

@{
    var countVP = 1;
    var countP = 1;
    var countN = 1;
}

<table class="table table-bordered table-striped" style="width: 90%;">
    <thead>
        <tr>
            <th colspan="2" style="text-align: center">
                <div class="input-group">
                    <input type="text" id="filterValue" class="form-control" style="width: 125px;" placeholder="Search for..."><span class="input-group-btn">
                        <button class="btn btn-default btnSearchTicket" id="btnSearchTicket" type="button">Go!</button>
                </div>
            </th>
            <th colspan="7" style="text-align: center;">Tickets List<span class="btn btn-xs btn-success btnCreate" id="btnCreate" style="float:right;">Create New</span></th>
        </tr>
        <tr class="success">
            <th>SNo.</th>
            <th>Project Name</th>
            <th>Create Date</th>
            <th>Status</th>
            <th>Priority</th>
            <th>Percent Complete</th>
            <th>Issue</th>
            <th>Assigned To</th>
            <th style="text-align: center;">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var tick in Model)
        {
            if(tick.Priority == "Very Urgent")
            {
                <tr>
                    <td><span class="glyphicon glyphicon-file" aria-hidden="true">  @(countVP++)</td>
                    <td>@tick.ProjectName</td>
                    <td>@tick.CreateDate</td>
                    <td>@tick.Status</td>
                    <td>@tick.Priority</td>
                    <td>@tick.PercentComplete</td>
                    <td>@tick.Issue</td>
                    <td>@tick.AssignedTo</td>
                    <td>
                        <span class="btn btn-xs btn-primary btnEdit" id="edit_@tick.Id">Edit</span>
                        <span class="btn btn-xs btn-info btnDetails" id="delails_@tick.Id">Details</span>
                        <span class="btn btn-xs btn-danger btnDelete" id="delete_@tick.Id">Delete</span>
                    </td>
                </tr>
            }
        }
        @foreach (var tick in Model)
        {
            if(tick.Priority == "Urgent")
            {
                <tr>
                    <td><span class="glyphicon glyphicon-text-height" aria-hidden="true">  @(countP++)</td>
                    <td>@tick.ProjectName</td>
                    <td>@tick.CreateDate</td>
                    <td>@tick.Status</td>
                    <td>@tick.Priority</td>
                    <td>@tick.PercentComplete</td>
                    <td>@tick.Issue</td>
                    <td>@tick.AssignedTo</td>
                    <td>
                        <span class="btn btn-xs btn-primary btnEdit" id="edit_@tick.Id">Edit</span>
                        <span class="btn btn-xs btn-info btnDetails" id="delails_@tick.Id">Details</span>
                        <span class="btn btn-xs btn-danger btnDelete" id="delete_@tick.Id">Delete</span>
                    </td>
                </tr>
            }
        }
        @foreach (var tick in Model)
        {
            if(tick.Priority == "Normal")
            {
                <tr>
                    <td><span class="glyphicon glyphicon-text-width" aria-hidden="true">  @(countN++)</td>
                    <td>@tick.ProjectName</td>
                    <td>@tick.CreateDate</td>
                    <td>@tick.Status</td>
                    <td>@tick.Priority</td>
                    <td>@tick.PercentComplete</td>
                    <td>@tick.Issue</td>
                    <td>@tick.AssignedTo</td>
                    <td>
                        <span class="btn btn-xs btn-primary btnEdit" id="edit_@tick.Id">Edit</span>
                        <span class="btn btn-xs btn-info btnDetails" id="delails_@tick.Id">Details</span>
                        <span class="btn btn-xs btn-danger btnDelete" id="delete_@tick.Id">Delete</span>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

ProjectManagementSoftware/Views/Tickets/Index.cshtml
@{
    ViewData["Title"] = "Projects Page";
}
<script src="~/Scripts/bootbox.min.js"></script>
<script src="~/js/Ticket.js"></script>

<div class="clearfix"><img src="~/Content/images/Ameba.jpg" width="500" height="66" style="float:left" /></div>
<br />
<br />
<br />
<div class="row" id="divList">

</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" id="modelContent">

        </div>
    </div>
</div>