ProjectManagementSoftware/Controllers/ReportsController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using MongoDB.Driver;
using MongoDB.Driver.Builders;
using MongoDB.Bson;
using Revoluza.Models;
using System;
using System.Linq;
using System.Configuration;
using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Diagnostics;
using System.Web.Helpers;

namespace Revoluza.Controllers
{
    public class ReportsController : Controller
    {
        private MongoDatabase mongoDatabase;

        public ReportsController()
        {
            // create connectionstring
            var connect = "mongodb://localhost";
            var Client = new MongoClient(connect);

            // get Reference of server
            var Server = Client.GetServer();

            // get Reference of Database
            mongoDatabase = Server.GetDatabase("School");
        }

        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult GetAll()
        {
            var _projects = mongoDatabase.GetCollection<Project>("Project");
            IList<Project> listProjects = new List<Project>();
            var getProjects = _projects.FindAs(typeof(Project), Query.NE("Name", "null"));
            foreach (Project proj in getProjects)
            {
                listProjects.Add(proj);
            }
            return PartialView("GetAll", listProjects);
        }

        public ActionResult GetPieChart()
        {
            int ntaCnt = 0;
            int inpCnt = 0;
            int comCnt = 0;
            int waCnt = 0;
            int ohCnt = 0;
            int canCnt = 0;
            int arCnt = 0;
            int cntChat = 0;

            var _projects = mongoDatabase.GetCollection<Project>("Project");
            var _task = mongoDatabase.GetCollection<Task>("Task");
            var _devBase = mongoDatabase.GetCollection<DevBase>("DevBase");
            var getProjects = _projects.FindAs(typeof(Project), Query.NE("Name", "null"));
            Chart[] arrChart = new Chart[getProjects.Count()];
            
            foreach (Project proj in getProjects)
            {
                ntaCnt = 0;
                inpCnt = 0;
                comCnt = 0;
                waCnt = 0;
                ohCnt = 0;
                canCnt = 0;
                string strChartTitle = "Project-wise Task Status: ["+proj.Name+"]";
                var getTasks = _task.FindAs(typeof(Task), Query.Matches("ProjectId", new BsonRegularExpression(proj.ProjectId.ToString(), "i")));
                foreach (Task tsk in getTasks)
                {
                    var getDBase = _devBase.FindAs(typeof(DevBase), Query.Matches("TaskId", new BsonRegularExpression(tsk.TaskId.ToString(), "i")));
                    foreach (DevBase dbase in getDBase)
                    {
                        if(dbase.Status.Equals("Not Started"))
                        {
                            ntaCnt++;
                        }
                        if(dbase.Status.Equals("In-Process"))
                        {
                            inpCnt++;
                        }
                        if(dbase.Status.Equals("Complete"))
                        {
                            comCnt++;
                        }
                        if(dbase.Status.Equals("Waiting Approval"))
                        {
                            waCnt++;
                        }
                        if (dbase.Status.Equals("On Hold"))
                        {
                            ohCnt++;
                        }
                        if (dbase.Status.Equals("Cancelled"))
                        {
                            canCnt++;
                        }
                    }
                }

                if(ntaCnt > 0)
                {
                    arCnt++;
                }
                if(inpCnt > 0)
                {
                    arCnt++;
                }
                if(comCnt > 0)
                {
                    arCnt++;
                }
                if(waCnt > 0)
                {
                    arCnt++;
                }
                if(ohCnt > 0)
                {
                    arCnt++;
                }
                if(canCnt > 0)
                {
                    arCnt++;
                }

                String [] arrTaskCount = new string[arCnt];
                String [] arrTaskName = new string[arCnt];
                arCnt = 0;

                if(ntaCnt > 0)
                {
                    arrTaskName[arCnt]="Not Assigned";
                    arrTaskCount[arCnt++] = ntaCnt.ToString();
                }
                if(inpCnt > 0)
                {
                    arrTaskName[arCnt] = "In-Process";
                    arrTaskCount[arCnt++] = inpCnt.ToString();
                }
                if(comCnt > 0)
                {
                    arrTaskName[arCnt] = "Complete";
                    arrTaskCount[arCnt++] = comCnt.ToString();
                }
                if(waCnt > 0)
                {
                    arrTaskName[arCnt] = "Waiting Approval";
                    arrTaskCount[arCnt++] = waCnt.ToString();
                }
                if(ohCnt > 0)
                {
                    arrTaskName[arCnt] = "On Hold";
                    arrTaskCount[arCnt++] = ohCnt.ToString();
                }
                if(canCnt > 0)
                {
                    arrTaskName[arCnt] = "Cancelled";
                    arrTaskCount[arCnt++] = canCnt.ToString();
                }

                arrChart[cntChat] = new Chart(width: 500, height: 350, theme: ChartTheme.Green)
                .AddSeries(
                    chartType: "pie",
                    legend: "Task Status",
                    xValue: arrTaskName,
                    yValues: arrTaskCount)
                .AddTitle(strChartTitle) 
                .Write();
            }
            return null;
        }

        public ActionResult GetRainfallChart()
        {
            int cntTask = 0;
            int cntPC = 0;
            int cntChat = 0;
            
            var _projects = mongoDatabase.GetCollection<Project>("Project");
            var _task = mongoDatabase.GetCollection<Task>("Task");
            var _devBase = mongoDatabase.GetCollection<DevBase>("DevBase");
            var getProjects = _projects.FindAs(typeof(Project), Query.NE("Name", "null"));
            Chart [] arrChart = new Chart[getProjects.Count()];

            foreach (Project proj in getProjects)
            {
                var getTasks = _task.FindAs(typeof(Task), Query.Matches("ProjectId", new BsonRegularExpression(proj.ProjectId.ToString(), "i")));
                String[] arrTask = new String[getTasks.Count()];
                String[] arrPC = new String[getTasks.Count()];
                String strChartTitle = "Project-wise Task / (% Complete) [" + proj.Name + "]";
                cntTask = 0;
                cntPC = 0;

                foreach (Task tsk in getTasks)
                {
                    arrTask[cntTask++] = tsk.Name;
                    var getQuery = Query<DevBase>.EQ(e => e.TaskId, tsk.TaskId.ToString());
                    var dBase = _devBase.FindOne(getQuery);
                    if (dBase != null)
                    {
                        arrPC[cntPC++] = dBase.PercentComplete.ToString();
                    }
                    else
                    {
                        arrPC[cntPC++] = "0";
                    }
                }

                arrChart[cntChat] = new Chart(width: 500, height: 350, theme: ChartTheme.Green)
                .AddSeries(
                    chartType: "bar",
                    chartArea: "Default",
                    axisLabel: "% Complete (Task)",
                    legend: "Tasks",
                    xValue: arrTask,
                    yValues: arrPC)
                .AddTitle(strChartTitle)
                .SetXAxis("Tasks", 0, 10)
                .SetYAxis("(% Complete)", 0, 100)
                .Write();
                
                //GetPieChartPTE(proj.ProjectId.ToString());
                //GetMonthsPTE(proj.ProjectId.ToString());
            }
            return null;
        }

        public ActionResult GetMonths()
        {
            int cntEmp = 0;
            int cntTemp = 0;

            var _employee = mongoDatabase.GetCollection<Employee>("Employee");
            var _task = mongoDatabase.GetCollection<Task>("Task");
            var _devBase = mongoDatabase.GetCollection<DevBase>("DevBase");
            var _projects = mongoDatabase.GetCollection<Project>("Project");
            
            var getProjects = _projects.FindAs(typeof(Project), Query.NE("Name", "null"));
            var getEmployees = _employee.FindAs(typeof(Employee), Query.NE("IsActive", false));
                        
            IList<Empty> lstEmpty = new List<Empty>();

            foreach (Employee emp in getEmployees)
            {
                lstEmpty.Add(new Empty() { Name = emp.Fullname });
                foreach (Project proj in getProjects)
                {
                    var getTasks = _task.FindAs(typeof(Task), Query.Matches("ProjectId", new BsonRegularExpression(proj.ProjectId.ToString(), "i")));
                    foreach (Task tsk in getTasks)
                    {
                        if (tsk.AssignedTo != null)
                        {
                            foreach (Employee empty in tsk.AssignedTo)
                            {
                                if (empty.EmpId.ToString().Equals(emp.EmpId.ToString()))
                                {
                                    lstEmpty[cntEmp].NoOfTasksAssigned = ++cntTemp;
                                }
                            }
                        }
                        else
                        {

ProjectManagementSoftware/Views/Reports/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ProjectManagementSoftware/Views/Reports/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ProjectManagementSoftware/Views/Reports/Create.cshtml
@model Revoluza.Models.Users

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title">Add New Record</h4>
</div>
<div class="modal-body">
    @using (Ajax.BeginForm("Create", "Home", new AjaxOptions {
        HttpMethod = "POST",
        UpdateTargetId = "divList", 
        InsertionMode = InsertionMode.Replace, 
        OnSuccess = "closeModal" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.PhoneNo, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.PhoneNo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PhoneNo, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
            </div>
            
            <div class="form-group modal-footer">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default btn-success" />
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    }
</div>

ProjectManagementSoftware/Views/Reports/Details.cshtml
@model Revoluza.Models.Users 

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title">Details Record</h4>
</div>
<div class="modal-body">
    <div>
        <table class="table table-bordered">
            <tr>
                <td>@Html.DisplayNameFor(model => model.UserName)</td>
                <td>@Html.DisplayFor(model => model.UserName)</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.Address)</td>
                <td>@Html.DisplayFor(model => model.Address)</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.Email)</td>
                <td>@Html.DisplayFor(model => model.Email)</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.PhoneNo)</td>
                <td>@Html.DisplayFor(model => model.PhoneNo)</td>
            </tr>
        </table>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default"
            data-dismiss="modal">
        Close
    </button>
</div>

ProjectManagementSoftware/Views/Reports/Edit.cshtml
@model Revoluza.Models.Users

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title">Edit Record</h4>
</div>
<div class="modal-body">

    @using (Ajax.BeginForm("Edit", "Home", new AjaxOptions
  {
      HttpMethod = "POST",
      UpdateTargetId = "divList",
      InsertionMode = InsertionMode.Replace,
      OnSuccess = "closeModal"
  }))
    {
        @Html.AntiForgeryToken()
         @Html.HiddenFor(model => model.Id)
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.PhoneNo, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.PhoneNo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PhoneNo, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group modal-footer">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Update" class="btn btn-default btn-primary" />
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    }
</div>

ProjectManagementSoftware/Views/Reports/GetAll.cshtml
@model IEnumerable<Revoluza.Models.Project>

@{
    var count = 1;
}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
 
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>Track Projects</title>
    </head>
    <body>
       <h1>Project Dashboard - Overview</h1>
       <div>
           @*<img src="/Reports/GetRainfallChart" />
           <img src="/Reports/GetPieChart" />
           <img src="/Reports/GetMonths" />*@
           @foreach(var proj in Model)
           {
                <br />
                <br />
                <div class="form-group">
                   <hr />
                   <p class="col-md-8" style="font-size: 17px; color: #538b01; font-weight: bold; font-style: italic; text-align: center;">Project Tracking Reports for [Project: @proj.Name]</p>
                   <br />
                   <hr />
                   <img src="@Url.Action("GetRainfallChartPT", "Reports", new { id = @proj.ProjectId })" />
                   <img src="@Url.Action("GetPieChartPT", "Reports", new { id = @proj.ProjectId })" />
                   <img src="@Url.Action("GetMonthsPT", "Reports", new { id = @proj.ProjectId })" />
                   <hr />
                </div>
           }
        </div>
    </body>
</html> 

ProjectManagementSoftware/Views/Reports/Index.cshtml
@{
    ViewBag.Title = "DashBoard";
}
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" 
        rel="stylesheet" type="text/css" />
    
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>

    <link href="@Url.Content("~/Content/themes/base/jquery.ui.core.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.datepicker.css")" rel="stylesheet"  type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.theme.css")" rel="stylesheet" type="text/css" />

    <script src="@Url.Content("~/Scripts/jquery.ui.core.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.ui.datepicker.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/DatePickerReady.js")" type="text/javascript"></script>
</head>
<script src="~/Scripts/bootbox.min.js"></script>
<script src="~/js/Report.js"></script>
<div class="clearfix"><img src="~/Content/images/Ameba.jpg" width="500" height="66" style="float:left" /></div>
<br />
<br />
<br />
<div class="row" id="divList">

</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" id="modelContent">

        </div>
    </div>
</div>